from __future__ import annotations

import logging
import os
import re
from typing import Any, Optional

logger = logging.getLogger(__name__)


class ProviderRateLimitError(RuntimeError):
    pass


class ProviderCallError(RuntimeError):
    pass


class AIRouterError(RuntimeError):
    pass


class AIRouter:
    def __init__(
        self,
        *,
        openai_key: Optional[str] = None,
        anthropic_key: Optional[str] = None,
        gemini_key: Optional[str] = None,
    ):
        self.keys = {
            "openai": openai_key or os.getenv("OPENAI_API_KEY"),
            "anthropic": anthropic_key or os.getenv("ANTHROPIC_API_KEY"),
            "gemini": gemini_key or os.getenv("GEMINI_API_KEY"),
        }
        self.routing = {
            "parse_rfq": ["gemini", "openai", "anthropic"],
            "verify_compliance": ["anthropic", "openai", "gemini"],
            "draft_sales_email": ["openai", "anthropic", "gemini"],
            "draft_supplier_rfq": ["openai", "anthropic", "gemini"],
        }

    def parse_rfq(self, text: str) -> dict[str, Any]:
        return self._route_call("parse_rfq", {"text": text})

    def verify_compliance(self, part_data: dict[str, Any]) -> dict[str, Any]:
        return self._route_call("verify_compliance", part_data)

    def draft_sales_email(self, quote_data: dict[str, Any]) -> dict[str, Any]:
        return self._route_call("draft_sales_email", quote_data)

    def draft_supplier_rfq(self, part_request: dict[str, Any]) -> dict[str, Any]:
        return self._route_call("draft_supplier_rfq", part_request)

    def _route_call(self, action: str, payload: dict[str, Any]) -> dict[str, Any]:
        providers = self.routing.get(action, [])
        if not providers:
            raise AIRouterError(f"No routing defined for action '{action}'")

        attempts: list[dict[str, str]] = []
        for index, provider in enumerate(providers):
            try:
                result = self._call_provider(action, provider, payload)
                return {
                    "provider": provider,
                    "model": self._model_name(provider, action),
                    "fallback_used": index > 0,
                    "result": result,
                }
            except (ProviderCallError, ProviderRateLimitError, ConnectionError, TimeoutError) as exc:
                logger.warning("Provider %s failed for %s: %s", provider, action, exc)
                attempts.append({"provider": provider, "error": str(exc)})

        raise AIRouterError(
            f"All providers failed for '{action}'",
            {"attempts": attempts},
        )

    def _call_provider(self, action: str, provider: str, payload: dict[str, Any]) -> dict[str, Any]:
        api_key = self.keys.get(provider)
        if not api_key:
            return self._mock_provider_response(action, provider, payload)

        # Real external clients are intentionally deferred in this repo.
        # Keep local/free workflow working while preserving deterministic output shape.
        return self._mock_provider_response(action, provider, payload)

    def _mock_provider_response(self, action: str, provider: str, payload: dict[str, Any]) -> dict[str, Any]:
        if action == "parse_rfq":
            text = str(payload.get("text", ""))
            return self._extract_quote_payload(text)
        if action == "verify_compliance":
            cert = str(payload.get("certificate_type", "UNKNOWN")).upper()
            compliant = cert in {"FAA 8130-3", "EASA FORM 1", "DUAL RELEASE"}
            return {
                "compliant": compliant,
                "certificate_type": cert,
                "notes": "Mock compliance verdict generated by ai_router",
            }
        if action == "draft_sales_email":
            customer = payload.get("customer_name", "Customer")
            part = payload.get("part_number", "requested part")
            return {
                "subject": f"Quote for {part}",
                "body": f"Hello {customer},\n\nThank you for your request. Please find your quote attached.\n\nBest regards,\nSales Team",
            }
        if action == "draft_supplier_rfq":
            part = payload.get("part_number", "unknown part")
            qty = payload.get("quantity", "N/A")
            return {
                "subject": f"RFQ Request - {part}",
                "body": (
                    "Hello,\n\n"
                    f"Please provide your best quote for part {part}, quantity {qty}, including lead time and cert details.\n\n"
                    "Regards,\nProcurement Team"
                ),
            }
        raise ProviderCallError(f"Unsupported action for provider {provider}: {action}")

    def _model_name(self, provider: str, action: str) -> str:
        if provider == "gemini" and action == "parse_rfq":
            return "gemini-2.5-flash"
        if provider == "anthropic" and action == "verify_compliance":
            return "claude-3.5-sonnet"
        if provider == "openai":
            return "gpt-4o"
        return f"{provider}-default"

    def _extract_quote_payload(self, text: str) -> dict[str, Any]:
        lower = text.lower()
        email_match = re.search(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}", text)
        supplier_email = email_match.group(0).lower() if email_match else "unknown@supplier.example"
        part_number_match = re.search(r"part(?:\s*number)?\s*[:=]\s*([^\r\n|]+)", text, flags=re.IGNORECASE)
        condition_match = re.search(r"condition\s*[:=]\s*([A-Za-z]{2,3})", text, flags=re.IGNORECASE)
        unit_cost_match = re.search(r"(?:price|unit\s*cost)\s*[:=]\s*\$?([0-9]+(?:\.[0-9]{1,2})?)", text, flags=re.IGNORECASE)
        qty_match = re.search(r"(?:quantity|qty)\s*[:=]\s*(\d+)", text, flags=re.IGNORECASE)
        lead_match = re.search(r"lead[_\s-]*time(?:\s*days)?\s*[:=]\s*(\d+)", text, flags=re.IGNORECASE)

        cert_type = "UNKNOWN"
        if "8130" in lower:
            cert_type = "FAA 8130-3"
        elif "easa" in lower:
            cert_type = "EASA Form 1"

        return {
            "supplier_email": supplier_email,
            "part_number": part_number_match.group(1).strip() if part_number_match else "",
            "condition": (condition_match.group(1).strip().upper() if condition_match else "NE"),
            "unit_cost": float(unit_cost_match.group(1)) if unit_cost_match else 0.0,
            "quantity_available": int(qty_match.group(1)) if qty_match else 0,
            "lead_time_days": int(lead_match.group(1)) if lead_match else 0,
            "certificate_type": cert_type,
        }
